FROM brunneis/python:3.8.3-ubuntu-20.04

WORKDIR /app

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt install software-properties-common -y
RUN add-apt-repository ppa:ondrej/php -y
RUN apt update
RUN apt install php7.2 php7.2-common php7.2-cli php7.2-fpm -y
RUN apt install php7.2-gd -y
COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt
COPY *.py ./
COPY kcaptcha ./kcaptcha
VOLUME ./output .data
ENTRYPOINT ["python", "generate.py"]


